openapi: 3.0.0
info:
  title: Import API
  version: 1.0.0
  description:
    The Medallia Import API enables import of data to Medallia
    Experience Cloud through a Data Import or Custom Import.
  termsOfService: https://medallia.com/about/legal/terms/api
servers:
  - url: 'https://{api-gateway-hostname}'
    variables:
      api-gateway-hostname:
        default: instance.apis.medallia.com
        description:
          The Medallia Experience Cloud hostname used to access
          Medallia Reporting
paths:
  /inbound/v1/{name}:
    post:
      tags:
        - Import
      description: Performs a data import
      operationId: import
      parameters:
        - in: path
          name: name
          description: The name of the importer
          required: true
          schema:
            type: string
            format: identifier
      requestBody:
        description: The data to be imported
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  additionalProperties:
                    type: string
                  example:
                    transaction_date: 2021-03-23T13:15:37-07:00
                    email: mary@example.medallia.com
                - type: array
                  items:
                    type: object
                    additionalProperties:
                      type: string
                    example:
                      transaction_date: 2021-03-23T13:15:37-07:00
                      email: mary@example.medallia.com
          text/csv:
            schema:
              type: string
          text/xml:
            schema:
              oneOf:
                - type: object
                  additionalProperties:
                    type: string
                  example:
                    transaction_date: 2021-03-23T13:15:37-07:00
                    email: mary@example.medallia.com
                - type: array
                  items:
                    type: object
                    additionalProperties:
                      type: string
                    example:
                      transaction_date: 2021-03-23T13:15:37-07:00
                      email: mary@example.medallia.com
      responses:
        200:
          description:
            The response to a data import that is processed synchronously
          headers:
            X-RateLimit-Limit-day:
              $ref: '#/components/headers/X-RateLimit-Limit-day'
            X-RateLimit-Remaining-day:
              $ref: '#/components/headers/X-RateLimit-Remaining-day'
            X-RateLimit-Limit-second:
              $ref: '#/components/headers/X-RateLimit-Limit-second'
            X-RateLimit-Remaining-second:
              $ref: '#/components/headers/X-RateLimit-Remaining-second'
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
            X-Medallia-Rpc-Request-Id:
              $ref: '#/components/headers/X-Medallia-Rpc-Request-Id'
          content:
            application/json:
              schema:
                type: object
                required:
                  - records
                  - duplicates
                  - rejects
                properties:
                  records:
                    type: integer
                    description: The number of records processed
                  duplicates:
                    type: integer
                    description:
                      The number of records found to match an existing
                      record in the system
                  rejects:
                    type: integer
                    description:
                      The number of records that could not be processed
                      for some reason
        202:
          description:
            The response to a data import that is processed asynchronously
          headers:
            X-RateLimit-Limit-day:
              $ref: '#/components/headers/X-RateLimit-Limit-day'
            X-RateLimit-Remaining-day:
              $ref: '#/components/headers/X-RateLimit-Remaining-day'
            X-RateLimit-Limit-second:
              $ref: '#/components/headers/X-RateLimit-Limit-second'
            X-RateLimit-Remaining-second:
              $ref: '#/components/headers/X-RateLimit-Remaining-second'
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
            X-Medallia-Rpc-Request-Id:
              $ref: '#/components/headers/X-Medallia-Rpc-Request-Id'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Object not found
          headers:
            X-RateLimit-Limit-day:
              $ref: '#/components/headers/X-RateLimit-Limit-day'
            X-RateLimit-Remaining-day:
              $ref: '#/components/headers/X-RateLimit-Remaining-day'
            X-RateLimit-Limit-second:
              $ref: '#/components/headers/X-RateLimit-Limit-second'
            X-RateLimit-Remaining-second:
              $ref: '#/components/headers/X-RateLimit-Remaining-second'
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
            X-Medallia-Rpc-Request-Id:
              $ref: '#/components/headers/X-Medallia-Rpc-Request-Id'
        412:
          description: Precondition failed
        500:
          description: Internal server error
      security:
        - mecOauth: []
components:
  headers:
    X-RateLimit-Limit-day:
      description: The number of requests allowed in total in a 24-hour period
      schema:
        type: integer
      example: 10000
      deprecated: true
    X-RateLimit-Remaining-day:
      description: The number of requests available to make in a 24-hour period
      schema:
        type: integer
      example: 10000
      deprecated: true
    X-RateLimit-Limit-second:
      description: The number of requests allowed in total in a 1-second period
      schema:
        type: integer
      example: 10
      deprecated: true
    X-RateLimit-Remaining-second:
      description: The number of requests available to make in a 1-second period
      schema:
        type: integer
      example: 10
      deprecated: true
    X-RateLimit-Limit:
      description: Indicates the request quota that is closest to reaching the limit amongst all request quotas. The first integer in the string represents the window closest to expiry.
      schema:
        type: string
      example: 10, 10;w=1, 100;w=86400
    X-RateLimit-Remaining:
      description: Indicates the amount of requests remaining in the specified time window returned from X-RateLimit-Limit
      schema:
        type: integer
      example: 10
    X-RateLimit-Reset:
      description: Indicates the time remaining in the specified time window returned from X-RateLimit-Limit, specified in seconds
      schema:
        type: integer
      example: 10
    X-Medallia-Rpc-Request-Id:
      description: The request ID, used by Medallia support for troubleshooting
      schema:
        type: string
        format: identifier
      example: 94615edd-d9d0-4921-8b3e-60615b3d3431
  securitySchemes:
    mecOauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://{reporting-hostname}/oauth/{company}/token
          scopes: {}
security:
  - mecOauth: []
